// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmMEIlk_ooDWWQonmNk11owj7bzQ1Hu40',
    appId: '1:234499502169:web:06d995fa2d95fbeceb4148',
    messagingSenderId: '234499502169',
    projectId: 'strikeforce-938e1',
    authDomain: 'strikeforce-938e1.firebaseapp.com',
    storageBucket: 'strikeforce-938e1.firebasestorage.app',
    measurementId: 'G-WZLYP1QG64',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdLONKh8VPfBoxnAToDDb8u-ssptqpj2s',
    appId: '1:234499502169:android:af54b8b81bdf453aeb4148',
    messagingSenderId: '234499502169',
    projectId: 'strikeforce-938e1',
    storageBucket: 'strikeforce-938e1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqjFpTfO4VoqecR3zMriTpo0fKncvYwzU',
    appId: '1:234499502169:ios:9fcc5006bd38c1beeb4148',
    messagingSenderId: '234499502169',
    projectId: 'strikeforce-938e1',
    storageBucket: 'strikeforce-938e1.firebasestorage.app',
    iosClientId: '234499502169-ju6uilhcld1c303jqatqfd3u57o5hjvg.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqjFpTfO4VoqecR3zMriTpo0fKncvYwzU',
    appId: '1:234499502169:ios:9fcc5006bd38c1beeb4148',
    messagingSenderId: '234499502169',
    projectId: 'strikeforce-938e1',
    storageBucket: 'strikeforce-938e1.firebasestorage.app',
    iosClientId: '234499502169-ju6uilhcld1c303jqatqfd3u57o5hjvg.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmMEIlk_ooDWWQonmNk11owj7bzQ1Hu40',
    appId: '1:234499502169:web:5b93451132a8ff09eb4148',
    messagingSenderId: '234499502169',
    projectId: 'strikeforce-938e1',
    authDomain: 'strikeforce-938e1.firebaseapp.com',
    storageBucket: 'strikeforce-938e1.firebasestorage.app',
    measurementId: 'G-WG6YP7P8C1',
  );
}
